version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /
      - /mirrors/*
    schedule:
      interval: daily
    commit-message:
      prefix: build
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
